### PR TITLE
Remove dice_bag and set configuration through environment variables directly

### PR DESCRIPTION
**Pull request by ykitamura-mdsol**
Title says all

@jcarres-mdsol @ejinotti-mdsol @cmcinnes-mdsol @ejennings-mdsol

### CODE REVIEW

**Comment by ykitamura-mdsol** [comment]
Since we are doing a major version upgrade, do we want to

- Prepend `MAUTH_` to all env vars
- Drop `RemoteRequestAuthenticator`

?

**Comment by ejinotti-mdsol** [comment]
I like both of those ideas, two yes's from me.

**Comment by jcarres-mdsol** [comment]
I can't comment on the second idea, but prepending env vars with `MAUTH` is beautiful

**Comment by ykitamura-mdsol** [comment]
I think no one is really using `RemoteRequestAuthenticator`. It is used to authenticate requests if you don't have app uuid and private key...

https://github.com/mdsol/mauth-client-ruby/blob/7975d2d5370e58ada7996ae6548bbbde081dee0a/lib/mauth/client.rb#L173-L179

**Comment by ejinotti-mdsol** [comment]
Also the route that is used by `RemoteRequestAuthenticator` is deprecated: https://github.com/mdsol/mauth/pull/299

**Review by ejinotti-mdsol — APPROVED** [review]

**Review by cmcinnes-mdsol — APPROVED** [review]
nice! thanks. wish we had a way via the GoCD config updates to rename a config var 🤔

**Pull request merged**
