### PR TITLE
version 4.0.1

### PR DESCRIPTION
**Pull request by jfeltesse-mdsol**
merging back to master so we can tag 4.0.1 on that commit.

@mdsol/team-10

### CODE REVIEW

**Comment by jfeltesse-mdsol** [comment]
should be, there are no changes, it's just a sync up.

@jcarres-mdsol what was the reason you didn't push the button at that time again? I have a faint memory of you arguing it's overkill but maybe I'm confused.

**Comment by jcarres-mdsol** [comment]
For Gems I find it overkill to do gitflow. It's just double number of PRs for, I think, no obvious benefit. We release to rubygems only specific revisions so it is not like adding things to master will break consumers.

If we merge this then I think  later PRs should target master directly.
What do you think?

**Comment by jfeltesse-mdsol** [comment]
I'm all for using good ol' master for developing, personally I don't like gitflow (I think it introduces more headaches than solutions).
If everyone agrees on this instead of merging this PR the best would be to close it and then I will nuke master, re-create it using develop and nuke develop for good.

**Comment by jcarres-mdsol** [comment]
wouldn't this PR sync dev and master so after merging develop can already be nuked?

**Comment by jfeltesse-mdsol** [comment]
It will introduce a useless merge commit. If we want to keep it as the legacy of those times it's 🆗  to have I guess. Either way.

**Comment by jcarres-mdsol** [comment]
you are right. I'd recreate and leave things pikapika

**Pull request merged**
