### PR TITLE
Fixing the $' which causes malformed headers on the request.  I belie…

### PR DESCRIPTION
**Pull request by johngluckmdsol**
I believe this is what was intended.  This will throw errors otherwise

### CODE REVIEW

**Comment by jfeltesse-mdsol** [comment]
Please don't commit `.DS_Store` and other IDE-specific files. A [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) might help.

**Comment by cabbott** [comment]
Please don't commit mauth keys,

**Comment by cabbott** [comment]
Sorry, meant to comment but clicked close instead. Please invalidate that mauth key (hoping it's just the randomly generated one that isn't registered)

**Comment by johngluckmdsol** [comment]
@jfeltesse-mdsol 
`what kind of errors we're talking about?`
404 - Bad URI

how come up until now such errors have not occurred
I don't think anyone uses this software.  Do you have telemetry that says otherwise?

what value this $' global variable can have a this time in the code
Not sure what you mean.  It was blank when I encountered it


needs a changelog update and version bump
needs specs

**Comment by jfeltesse-mdsol** [comment]
> 404 - Bad URI

We'll need much more info and context to be able to confirm the bug lies in mauth-client-ruby, can you follow up by email with all the details (which are bound to contain non public info -- hence not here on the public space).

>  I don't think anyone uses this software. Do you have telemetry that says otherwise?

Please check pikapika. I'll let you appreciate that every single ruby platform service uses mauth.

>  Not sure what you mean. It was blank when I encountered it

What I mean is this `$'` global variable stands for "The string following the match in the last successful pattern match. This variable is local to the current scope. Read only. Thread local." so it can take different values. I'm wondering what is the typical value you'd encounter in a normal scenario. Could be the services you're trying to make interact are not supplying the mauth data correctly, which makes the match fail and "corrupts" the headers there. If this theory is true then this gem is not responsible although it should handle such cases more gracefully.

**Comment by jfeltesse-mdsol** [comment]
The DS_Store file is still here btw. Please add this to your personal global gitignore file instead of this gem's gitignore file since it's macOS specific and it's not this gem's gitignore file responsibility to cater to the various OS metadata files out there.

**Comment by jfeltesse-mdsol** [comment]
About the "needs specs" part, sorry I might have been unclear, if that change is indeed warranted it should have either more or at least modified specs. The fact that the code has changed but the specs pass mean that this area is not covered properly.

**Comment by johngluckmdsol** [comment]
Nevermind.  Closing

**Pull request closed without merging**
